# Usa una imagen base de Node.js
FROM node:18

# Copia el archivo package.json y package-lock.json al directorio de trabajo
COPY src/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de tu aplicación al directorio de trabajo
COPY src/ .

# Expone el puerto en el que la aplicación estará escuchando
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
